# .github/workflows/ci-cd.yaml
name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint Lambda and Glue scripts
        run: |
          flake8 lambda/wistia_lambda.py
          flake8 glue/transform_dim_media.py
          flake8 glue/transform_dim_visitor.py
          flake8 glue/transform_fact_media_engagement.py

  # Optional: Lambda deploy with AWS CLI (needs AWS secrets set in repo)
  deploy-lambda:
    if: github.ref == 'refs/heads/main'
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Zip Lambda function
        run: |
          cd lambda
          zip -r wistia_lambda.zip wistia_lambda.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # change to your region

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code --function-name wistia-ingestion-lambda --zip-file fileb://lambda/wistia_lambda.zip
